### ISSUE TITLE
bootstrap 4 beta support

### ISSUE THREAD

**Issue by ahmadalli** [thekalinga/bootstrap4-vscode#12]

**Comment by thekalinga** [comment]
Hi,

I'm not actively working on bootstrap. So not sure how many snippets would be affected & am having very lil time work on this right now.

Would appreciate if someone can submit a pull request after modifying the snippets (these are vanilla html snippets) under `src/util/resources/bootstrap` directory.

**Comment by thekalinga** [comment]
Not applicable anymore as newer versions are alreayd added
