### ISSUE TITLE
Does not work in a JSX File

### ISSUE THREAD

**Issue by ekundayo-ab** [thekalinga/bootstrap4-vscode#21]
Hi, this package seems not to work in a `JSX` file in **Visual Studio Code**

**Comment by Eventyret** [comment]
I don't think it will work as the snippets are set up for HTML not JS / JSX

**Comment by DevJMD** [comment]
@Eventyret - not sure why. Emmet can support any language with the following specifc config setting:

```json
{
        "emmet.includeLanguages": {
	        "jsx": "html"
        }
}
```

**Comment by Eventyret** [comment]
I would guess if you set it to HTML then use the shortcode. then switch to JSX it should work fine ? but as you said @DevJMD it should work with JSX IF user has set jsx to html.
But the plugin is not emmet, its snippets built into vscode

**Comment by doreancl** [comment]
you can udpate the package.json file, on %USERPROFILE%\.vscode\extensions\thekalinga.bootstrap4-vscode-4.1.1\package.json and add:

```
{
	"language": "javascriptreact",
	"path": "./snippets.json"
},
{
	"language": "javascript",
	"path": "./snippets.json"
},
```

this work for me

**Comment by lorenzo-w** [comment]
@doreancl This worked for me too, thanks a lot! I see no reason why this shouldn't be supported by default.

**Comment by Eventyret** [comment]
@doreancl implementing this and making a new release :) - Thank you

**Comment by thekalinga** [comment]
Published a new version with the fix. Please verify and comment if there are any issues
