### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by sayemon10** [thekalinga/bootstrap4-vscode#28]
b4-navbar....<Tab>
doesn't include normal bootstrap hamburger option for mobile designing.
I mean, when i resize the window for coding on mobile version, there is no menu icon or Hamburger icon..
![capture](https://user-images.githubusercontent.com/35277447/37964361-022c0adc-31e3-11e8-9b31-65e2183d517c.PNG)

**Comment by HarryAdney** [comment]
Make sure you give it the dark or light classname, as appropriate:

- Use navbar-dark to produce light/white colored links and toggler
- Use navbar-light to produce dark/gray colored links and toggler

**Comment by sayemon10** [comment]
The problem is here
<button class="navbar-toggler hidden-lg-up" aria-expanded="false" aria-controls="collapsibleNavId" aria-label="Toggle navigation" type="button" data-target="#collapsibleNavId" data-toggle="collapse">
[here is no SPAN that will call the Hamburger menu</button>

**Comment by sayemon10** [comment]
@thekalinga

**Comment by thekalinga** [comment]
@sayemon10 I'm not working on bootstrap anymore & so am not fully aware of the changes required.

Would appreciate if you can submit a pull request. Making changes is as simple as adding/editing a simple html template. Please refer to https://github.com/thekalinga/bootstrap4-vscode#contribution-guidelines on how you can contribute
