### ISSUE TITLE
Enable on Twig and Blade files as well

### ISSUE THREAD

**Issue by minthemiddle** [thekalinga/bootstrap4-vscode#3]
This should be enabled on *.twig and *.blade.php files as well as these are HTMLish filetypes as well. And this is just for PHP, same for Jinja and Django Template Format for Python and probably a couple of other templating formats.

**Comment by minthemiddle** [comment]
See my [PR](https://github.com/thekalinga/bootstrap4-vscode/pull/4)

**Comment by thekalinga** [comment]
Made a new release, please verify

**Comment by minthemiddle** [comment]
Works just as expected! Thanks
