### ISSUE TITLE
Update it to 4.1.1

### ISSUE THREAD

**Issue by ayoubkhan558** [thekalinga/bootstrap4-vscode#33]
I like this extension, but please update this to Bootstrap 4.1.1, Thanks in Advance.

**Comment by thekalinga** [comment]
I have just published a newer version of the plugin. Can you please verify & confirm if the newer version has any issues

**Comment by ayoubkhan558** [comment]
Thank You but Now Bootstrap 4.1.2 has come.

**Comment by thekalinga** [comment]
Most of the people woudl like to use the latest version which is 4.1.2

Which is I updated it to 4.1.2

**Comment by ayoubkhan558** [comment]
Thank you so much for updating it to bootstrap 4.1.2, 

but
Please 
mention in Readme.md that what Bootstrap version you are using.
as
![screenshot 95](https://user-images.githubusercontent.com/20210961/42878138-67ff7dec-8aa5-11e8-8696-9258ac76a713.png)

Also add this in changelog.
