### ISSUE TITLE
Some FA4 icons snippets not available

### ISSUE THREAD

**Issue by giovdi** [thekalinga/bootstrap4-vscode#37]
Hi all,
some FA4 icons are not included in snippets.json.
Is this normal?

For example, the "save" icon is available only for the "fa5-" prefix and not for the "fa4-" one.

Probably is a build problem: seems that FA4 and FA5 icons have the same snippet name and the second one overwrites the first one.

Thank you.

**Comment by thekalinga** [comment]
try ` floppy-o`

**Comment by thekalinga** [comment]
https://fontawesome.com/v4.7.0/icons/

**Comment by giovdi** [comment]
If readme says that `save` icon is supported, why should I use `floppy-o`?
And what about chevrons? None of them are supported as FA4 icon.

**Comment by thekalinga** [comment]
@giovdi Good catch. Looks like I need to update the readme & a warning informing the users to use the appropriate icon names given in the respective version of fontawesome (needs to check if )

Please note that this plugin only generates the snippets & does not modify fontawesome stylesheet in any way (and why should we). So, the snippets given must be seen as a superset that includes all versions of files

As per `chevron`, looks like its a bug. I need to refactor the code to pull the data from a different source than whats currently used

I am currently busy with my own stuff. I will need to unify both vscode & intellij versions, which will take a while before I make any changes to the plugin

**Comment by thekalinga** [comment]
Just found the actual source that list all the icons available in fa4

https://raw.githubusercontent.com/FortAwesome/Font-Awesome/v4.7.0/src/icons.yml

Will use that as a source later

**Comment by giovdi** [comment]
Thank you @thekalinga, no rush ;)

**Comment by thekalinga** [comment]
Released a new version v6.0.0 with the fix. Also the project is now migrated to https://github.com/1tontech/bootstrap4-snippets
