### ISSUE TITLE
All snippet tab-stop choices are broken (need delimiting | )

### ISSUE THREAD

**Issue by lastobelus** [thekalinga/bootstrap4-vscode#45]
Not sure if vscode changed snippet syntax or what, but all your tab-stop choices are broken.

These regexes will fix them all:

find: `(\$\{\d+:)([^|}]+\|[^}]+)\}`
replace: `$1|$2|}`

find: `([^:])\|(?=[|\w]+\})`
replace: `$1,`

find: `:\|`
replace: `|`

**Comment by thekalinga** [comment]
Released a new version v6.0.0 with the fix. Also the project is now migrated to https://github.com/1tontech/bootstrap4-snippets
