### ISSUE TITLE
Generated carousel control markups not working

### ISSUE THREAD

**Issue by monkalways** [thekalinga/bootstrap4-vscode#5]
The carousel control markups generated by "b4-carousel-default" and "b4-carousel-caption" are not working properly. 

`<a class="left carousel-control" href="#carouselId" role="button" data-slide="prev">
    <span class="icon-prev" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carouselId" role="button" data-slide="next">
    <span class="icon-next" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>`

According to the latest Bootstrap 4 alpha document, it should be 

`<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>`

**Comment by thekalinga** [comment]
I'm currently occupied with my own stuff. Will you be able to submit a pull request for this?

You can find the files under question at `src/util/resources/bootstrap/components/carousel/default.html` & `src/util/resources/bootstrap/components/carousel/caption.html`

These are simple http snippets that follow [sublime format](docs.sublimetext.info/en/latest/extensibility/snippets.html)

**Comment by monkalways** [comment]
Yes, the pull request is created. Please take a look.

**Comment by thekalinga** [comment]
Will merge and give a build. Can you please check?

**Comment by thekalinga** [comment]
Released a new version. Can u please check

**Comment by monkalways** [comment]
The change looks good.
