### ISSUE TITLE
Doesn't work with inline templates

### ISSUE THREAD

**Issue by fishlurk** [thekalinga/bootstrap4-vscode#6]
I mainly use inline templates instead of external html files, since I try to keep components lightweight. And these snippets do not work in inline html, only in html files.

**Comment by thekalinga** [comment]
Inline within typescript files?

**Comment by fishlurk** [comment]
Yes

**Comment by thekalinga** [comment]
Just published a newer version. Please verify

**Comment by fishlurk** [comment]
Verified! Works perfectly, thanks.
